name: Shell Script Syntax Checker

on:
  push:
  pull_request:

jobs:
  shell-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check Shell Script Syntax
      run: |
        find . -type f -name '*.sh' -exec shellcheck {} \;
